name: Deploy to server
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 ${{ secrets.ARTIFACT_HOST }} >> ~/.ssh/known_hosts
          sudo apt-get install sshpass

      - name: Deploy to server
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} <<'ENDSSH'
          # Navigate to the application directory
          cd ${{ secrets.APP_PATH }}

          # Terminate existing screen sockets
          pkill screen

          # Ensure no process is using port 8000 (replace 8000 with your port if necessary)
          fuser -k 8000/tcp || echo "No process using port 8000"

          # Wait briefly to allow port to be freed
          sleep 5

          # Pull the latest code
          git pull

          # Start a new screen session and deploy the app
          screen -dmS PES
          screen -S PES -X stuff 'source ${{ secrets.ENV_PATH }}\n'
          screen -S PES -X stuff 'pip install .\n'
          screen -S PES -X stuff 'python ${{ secrets.START_SCRIPT_PATH }}\n'

          # List screen sessions for verification
          screen -ls
          ENDSSH
